on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy website
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4

      # Install Dependencies
      - name: Install Dependences
        run: npm ci --legacy-peer-deps

      # Build
      - name: Build Project
        run: npm run build

      # sync files via FTP
      - name: Sync files via FTP
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{secrets.FTP_SERVER}}
          remote-user: ${{secrets.FTP_USER}}
          private-ssh-key: ${{secrets.FTP_SSH_KEY}}
          destination-path: ${{env.SERVER_DIR}}
          source-path: ${{env.LOCAL_DIR}}