on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy website
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4

      # Install Dependencies
      - name: Install Dependences
        run: npm ci --legacy-peer-deps

      # Build
      - name: Build Project
        run: npm run build

      # sync files via FTP
      - name: Sync files via FTP
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{secrets.FTP_SERVER}}
          remote-user: ${{secrets.FTP_USER}}
          private-ssh-key: ${{secrets.FTP_SSH_KEY}}
          destination-path: ${{env.SERVER_DIR}}
          source-path: ${{env.LOCAL_DIR}}
          ssh-port: '22'
          rsync-options: '--archive --verbose --compress --human-readable --progress --delete-after --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore --exclude=**/node_modules/** --exclude=.cache/ --exclude=.idea/ --exclude=src/ --exclude=.prettierignore --exclude=.prettierrc --exclude=gatsby-config.ts --exclude=package.json --exclude=package-lock.json --exclude=tsconfig.json'